spring:
  application:
    name: familyfinance

  datasource:
    url: jdbc:mysql://localhost:3306/family_finance_db?createDatabaseIfNotExist=true
    username: root
    password: Aditya@8088

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  ai:
    openai:
      api-key: YOUR_OPENAI_API_KEY



